# Generated by Django 3.2.14 on 2022-07-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_movements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='movement',
            name='security_movement_type',
            field=models.CharField(max_length=20),
        ),
    ]
